#create variables for the assignment
#create the input
#create the print statement that makes the story

noun = input("Give me a noun")
plural_noun = input("Give me a plural noun")
adjective = input("Give me an adjective")
animated_character = input("Give me the name of an animated character")
m_country = input("Give me a country that starts with an M")
country_part_two = input("Give me another country")
shape = input("Give me a shape")
triple_digit = input("Give me a triple digit number")
distance = input("Give me a metric of distance")
color = input("Give me a color")
earth_shape = input("Give me a 3D Shape")
emotion = input("Give me an emotion")
event = input("Give me an event")
communication = input("Give me a form of communication")
emotion_part_two = input("Give me another emotion")
public_objects = input("Give me a group of objects")
physical_characteristic = input("Give me a physical feature")
place = input("Give me a place")
direction = input("Give me a direction")
color_2 = input("Give me another color")
object = input("Give me an object in its plural form")
thing = input("Give me a thing also in plural form")
action_ing = input("Give me an action that ends in ING")
object_2 = input("Give me another object")
purpose = input("Give me a purpose for doing something")
fake_movie = input("Give me a fake movie name")


print("In 1981, the US launched the first real space",noun,".")
print("Its name was Columbia and it was piloted by two brave",plural_noun,".")
print("Columbia was very",adjective,".")
print("The pilots were chosen by the very famous",animated_character,".")
print("Columbia took off from",m_country,", but it was supposed to take off from",country_part_two,".")
print("The pilots of the Columbia wanted to determine if the Earth was really a",shape,".")
print("When the Columbia reached",triple_digit," thousand",distance," the pilots could see that the sun was actually",color,".")
print("However, that was not what the pilots were here for. They turned to look at the Earth and discovered it was actually a",earth_shape,".")
print("The pilots felt",emotion," and one of them threw a",event," in reaction to this news.")
print("The pilots informed",animated_character," of this news through a",communication,".")
print("When",animated_character," heard the news they felt",emotion_part_two,".")
print("The public, who was a group of",public_objects," stood there and looked like",physical_characteristic,".")
print("The group of",public_objects,"went to",place," in response to the news")
print("After the job was done, the pilots turned the Columbia",direction,"and started to head back home.")
print("As the pilots were reentering the atmosphere, the shield around Columbia became",color_2,".")
print("The pilots made it through the atmosphere and landed in a field of",object,".")
print("The pilots exited the Columbia and was met by a group of wild",thing,".")
print("The",thing," surrounded the Columbia and started to",action_ing,"Columbia.")
print("The Columbia was turned into a",object_2," and the public was in awe. The public decided to put the Columbia in a museum for",purpose,"purposes.")
print("The Columbia was never flown again, but was honored in movies like",fake_movie,".")

